import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import worker from '../dist/server/index.js';
const sqlite=new DatabaseSync(':memory:');sqlite.exec(readFileSync(new URL('../drizzle/0000_blushing_lake.sql',import.meta.url),'utf8'));
const DB={prepare(sql){return {bind(...args){return {async run(){const r=sqlite.prepare(sql).run(...args);return {meta:{changes:r.changes}};},async first(){return sqlite.prepare(sql).get(...args);}};},async first(){return sqlite.prepare(sql).get();}};}};
const origin='https://vibe-social-nights.bb0949.chatgpt.site';
const call=(path,method='GET',data,token,from=origin)=>worker.fetch(new Request(origin+'/api/cinema'+path,{method,headers:{Origin:from,'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},body:data?JSON.stringify(data):undefined}),{DB});
assert.equal((await call('','POST',{url:'http://localhost/x.mp4'})).status,400);
assert.equal((await call('','POST',{url:'https://www.youtube.com/watch?v=M7lc1UVf-VE'},null,'https://evil.example')).status,403);
const created=await call('','POST',{url:'https://youtu.be/M7lc1UVf-VE'});assert.equal(created.status,201);const host=await created.json();
const guest=await (await call('/'+host.id)).json();assert(!('hostToken' in guest));assert(!('host_hash' in guest));assert.equal(guest.media.id,'M7lc1UVf-VE');
const state={paused:false,position:25,version:1};assert.equal((await call('/'+host.id,'PATCH',state)).status,403);
assert.equal((await call('/'+host.id,'PATCH',{...state,position:-1},host.hostToken)).status,400);
assert.equal((await call('/'+host.id,'PATCH',state,host.hostToken)).status,200);
const secondGuest=await (await call('/'+host.id)).json();assert.equal(secondGuest.position,25);assert.equal(secondGuest.paused,false);assert.equal(secondGuest.version,2);
assert.equal((await call('/'+host.id,'PATCH',state,host.hostToken)).status,409);
assert.equal((await call('/'+host.id,'DELETE')).status,403);
assert.equal((await call('/'+host.id,'DELETE',undefined,host.hostToken)).status,200);
assert.equal((await call('/'+host.id)).status,404);
sqlite.close();console.log('PASS shared cinema: real SQLite migration, create/join, shared timeline, host isolation, stale update conflict, end session. D1 transport adapted locally; devices not tested.');
