'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const source=fs.readFileSync('public/app.js','utf8');
const cloudSource=fs.readFileSync('public/cloud-ui.js','utf8');
const html=fs.readFileSync('public/index.html','utf8');
const css=fs.readFileSync('public/style.css','utf8');
const headers=fs.readFileSync('public/_headers','utf8');
assert(!/\bon(?:click|submit|change)\s*=/.test(source+html));
assert(!/\beval\s*\(|new\s+Function\s*\(/.test(source));
assert(!/unsafe-inline|unsafe-eval/.test(headers+html));
for(const directive of ["default-src 'none'","script-src 'self'","script-src-attr 'none'","connect-src 'self'","form-action 'none'","base-uri 'none'"])assert(html.includes(directive));
const supabaseOrigin='https://hsvcdyxelshvgofjvlim.supabase.co';
assert(html.includes(`connect-src 'self' ${supabaseOrigin}`));
assert(headers.includes(`connect-src 'self' ${supabaseOrigin}`));
assert(headers.includes('Permissions-Policy: camera=(self)'));
const workerSource=fs.readFileSync('server/worker.mjs','utf8'),cloudServer=fs.readFileSync('server/cloud.mjs','utf8');assert(!workerSource.includes('vibe-social-nights.bb0949.chatgpt.site'));assert(cloudServer.includes("req.headers.get('Origin')!==url.origin"));
for(const expected of ["authScreen='welcome'","openAuthForm('signup')","openAuthForm('login')","authScreen='recovery'","cloudAuthDirect('recover'"])assert(cloudSource.includes(expected));assert(!cloudSource.includes('/auth/v1/'));assert(cloudSource.includes("cloudAPI('auth/'+action,'POST',data)"));
assert(!/@import|https?:\/\//.test(css));
assert(!/XMLHttpRequest|sendBeacon|WebSocket/.test(source));assert(!source.includes('api.openai.com'));
assert.deepEqual([...source.matchAll(/localStorage\.setItem\('([^']+)'/g)].map(m=>m[1]),['vibe-language','vibe-language','vibe-demo-consent']);
for(const asset of [...html.matchAll(/(?:src|href)="([^"#]+)"/g)].map(m=>m[1]))assert(fs.existsSync('public/'+asset));
const events={},windowEvents={},revoked=[];
const app={innerHTML:'',replaceChildren(){this.innerHTML=''}};
const dialog={innerHTML:'',open:false,showModal(){this.open=true},close(){this.open=false},replaceChildren(){this.innerHTML=''}};
const toast={textContent:'',classList:{add(){},remove(){}}};
const doc={hidden:false,documentElement:{},addEventListener(name,fn){events[name]=fn},querySelector(s){return s==='#app'?app:s==='#create'?dialog:s==='#toast'?toast:s==='.messages'?{scrollTop:0}:null}};
let resolveStream,streamStops=0;
const stream={getTracks(){return [{stop(){streamStops++}}]}};
const ctx={queueMicrotask(){},document:doc,window:{isSecureContext:true,scrollTo(){},addEventListener(name,fn){windowEvents[name]=fn}},navigator:{mediaDevices:{getUserMedia(){return new Promise(r=>resolveStream=r)}}},localStorage:{getItem(){return null},setItem(){}},setTimeout(){},clearTimeout(){},setInterval(){},clearInterval(){},URL:{revokeObjectURL(x){revoked.push(x)},createObjectURL(){return 'blob:test'}},FormData:class{constructor(x){this.x=x}get(k){return this.x[k]}},MediaRecorder:class{},Blob};
vm.createContext(ctx);
const instrumented=source.replace(/\}\)\(\);\s*$/,`globalThis.api={moveMicHold,finishNote,safeProfileLink,profileLinkView,recordNote,choosePhoto,stopNote,endMicHold,go,join,render,fillCreate,recordAction,selectMedia,clearRecording,sendRoom,createRoom,sendChat,handlerMaps,raiseHand,submitWord,blockUser,unblockUser,saveReport,clearDemoData,permittedText,authPreview,checkSignupConsent,messageView,sendAttachment,openProfileEdit,saveProfileEdit,moveGallery,removeGallery,compressPhoto,prepareAvatarPhoto,cancelLinkPreviews,cancelMicHold,togglePrompt,parseMediaLink,set(s){eval(s)},get(s){return eval(s)}};})();`);
vm.runInContext(instrumented,ctx);
const a=ctx.api;
ctx.URL=class extends URL {static revokeObjectURL(x){revoked.push(x)} static createObjectURL(){return 'blob:test'}};
assert.equal(a.parseMediaLink('https://youtu.be/M7lc1UVf-VE').type,'youtube');
assert.equal(a.parseMediaLink('https://youtube.com.evil.test/watch?v=M7lc1UVf-VE').type,'link');
assert.equal(a.parseMediaLink('javascript:alert(1)'),null);
assert.equal(a.parseMediaLink('https://127.0.0.1/movie.mp4'),null);
assert.equal(a.parseMediaLink('https://example.com/movie.mp4').type,'video');

for(const lang of ['ar','en'])for(const page of ['home','plus','profile','friends','chats','auth','safety','community','privacy','account','terms','support','onboarding','settings','likes']){
 a.set(`lang='${lang}'`);a.go(page);assert(app.innerHTML.length>1000);assert(!app.innerHTML.includes('undefined'));assert(!/\son\w+=|style="/.test(app.innerHTML));
 if(lang==='en')assert(!/[\u0600-\u06ff]/.test(app.innerHTML.replace(/<[^>]*>/g,'').replaceAll('العربية','')));
}
a.go('home');const stale=[...a.handlerMaps.app.keys()][0];a.render();assert(!a.handlerMaps.app.has(stale));
a.fillCreate();const dialogId=[...a.handlerMaps.dialog.keys()][0];a.render();assert(a.handlerMaps.dialog.has(dialogId));
const roomEvent={preventDefault(){},target:{title:'<img src=x onerror=alert(1)>',type:'flash',category:'1'}};
a.set('plus=true;communityAccepted=true');a.createRoom(roomEvent);const flashId=a.get('current.id');assert(app.innerHTML.includes('&lt;img'));
a.sendRoom({preventDefault(){},target:{message:{value:'<script>alert(1)</script>'}}});a.go('home');assert(!a.get(`rooms.some(r=>r.id===${flashId})`));assert(!a.get(`Object.hasOwn(roomMessages,${flashId})`));
a.createRoom({preventDefault(){},target:{title:'Invalid',type:'__proto__',category:1}});assert.equal(a.get('view'),'home');
a.join(3);a.set("lang='en';game='words'");a.submitWord({preventDefault(){},target:{word:{value:'sun'}}});assert.equal(a.get('score'),10);a.submitWord({preventDefault(){},target:{word:{value:'sun'}}});assert.equal(a.get('score'),10);
a.set('ghost=true');a.raiseHand();assert(!a.get('raised'));
a.set("localMessages={};chatPerson=3;communityAccepted=true");a.go('chats');for(let i=0;i<105;i++)a.sendChat({preventDefault(){},target:{message:{value:'hello'}}});assert.equal(a.get('localMessages[3].length'),100);
a.sendChat({preventDefault(){},target:{message:{value:'x'.repeat(2001)}}});assert.equal(a.get('localMessages[3].length'),100);

a.blockUser(3);assert(a.get('blockedUsers.has(3)'));a.go('chats');assert.notEqual(a.get('chatPerson'),3);a.unblockUser(3);assert(!a.get('blockedUsers.has(3)'));
assert.equal(a.permittedText('i will kill you'),false);assert.equal(a.permittedText('hello friends'),true);
a.saveReport({preventDefault(){},target:{reason:'0',details:'example'}},'user',3);assert.equal(a.get('localReports.length'),1);
a.go('safety');assert(app.innerHTML.includes('Not submitted'));
for(const id of [3,4,5,8])a.blockUser(id);a.go('chats');assert(app.innerHTML.includes('No chats available'));a.unblockUser(3);a.go('chats');assert.equal(a.get('chatPerson'),3);for(const id of [4,5,8])a.unblockUser(id);

a.set("authMode='signup';signupAccepted=false");assert.equal(a.checkSignupConsent(),false);a.set('signupAccepted=true');assert.equal(a.checkSignupConsent(),true);
a.authPreview({preventDefault(){},target:{username:{value:'vibe.test'},reset(){}}});assert(a.get("signupConsent.terms==='prototype-v8'"));assert.equal(a.get('view'),'onboarding');for(const step of [0,1,2]){a.set('onboardingStep='+step);a.render();assert(!app.innerHTML.includes('undefined'));}a.set("profileBio='<script>unsafe</script>'");a.go('profile');assert(app.innerHTML.includes('&lt;script&gt;'));a.go('auth');assert(app.innerHTML.indexOf('Create new account')<app.innerHTML.indexOf('id="signup-consent"'));
a.set("plus=true;communityAccepted=true;chatPerson=3;attachment={kind:'photo',url:'blob:photo',target:3,handler:'sendChat'}");a.sendAttachment('sendChat');assert.equal(a.get("localMessages[3].at(-1).kind"),'photo');assert.equal(a.get('attachment'),null);
assert(a.messageView({kind:'text',text:'<script>x</script>',id:44},'chat',3,0).includes('&lt;script'));
a.openProfileEdit();assert(app.innerHTML.includes('media-grid'));a.set("editDraft.photos=['blob:one','blob:two'];editDraft.bio='edited';editDraft.prompts=[{id:0,answer:'<script>test</script>'}]");a.moveGallery(1,-1);assert.equal(a.get('editDraft.photos[0]'),'blob:two');a.set("editTab='preview'");a.render();assert(app.innerHTML.includes('&lt;script&gt;'));a.saveProfileEdit();assert.equal(a.get('galleryPhotos.length'),2);a.openProfileEdit();a.removeGallery(0);a.go('profile');assert.equal(a.get('galleryPhotos.length'),2);assert(!revoked.includes('blob:two'));a.openProfileEdit();a.removeGallery(0);a.saveProfileEdit();assert(revoked.includes('blob:two'));a.set('preferences.ageMin=18;preferences.ageMax=80');a.go('settings');assert(app.innerHTML.includes('min="18"'));
a.openProfileEdit();a.set('editDraft.prompts=[]');for(let i=0;i<7;i++)a.togglePrompt(i);assert.equal(a.get('editDraft.prompts.length'),6);a.togglePrompt(2);a.togglePrompt(7);assert.equal(a.get('editDraft.prompts.length'),6);assert(a.get('editDraft.prompts.some(x=>x.id===7)'));assert.equal(a.get('promptChoices.length'),58);a.set("editDraft.prompts[0].answer='<img onerror=evil>'");a.render();assert(app.innerHTML.includes('&lt;img'));a.go('profile');
a.set("micHold={timer:12};pendingPreviews.set('test',{abort(){globalThis.abortedPreview=true}})");a.cancelMicHold();a.cancelLinkPreviews();assert.equal(a.get('micHold'),null);assert.equal(a.get('pendingPreviews.size'),0);assert.equal(ctx.abortedPreview,true);
const originalGet=ctx.localStorage.getItem;ctx.localStorage.getItem=k=>k==='vibe-demo-consent'?'v8':null;a.set("authMode='signup';signupAccepted=false");assert.equal(a.checkSignupConsent(),true);ctx.localStorage.getItem=originalGet;
assert.equal(a.safeProfileLink('javascript:alert(1)'),null);assert.equal(a.safeProfileLink('https://user:pass@example.com'),null);assert.equal(a.safeProfileLink('https://127.0.0.1/x'),null);assert.equal(a.safeProfileLink(''), '');assert.equal(a.safeProfileLink('https://example.com/me'),'https://example.com/me');
a.openProfileEdit();a.set("editDraft.link='javascript:alert(1)'");a.saveProfileEdit();assert.equal(a.get('view'),'edit');a.set("editDraft.link='https://example.com/me'");a.saveProfileEdit();assert.equal(a.get('profileLink'),'https://example.com/me');assert(app.innerHTML.includes('noopener noreferrer'));assert(app.innerHTML.indexOf('interest-summary')<app.innerHTML.indexOf('profile-bio'));a.openProfileEdit();a.set("editDraft.link=''");a.saveProfileEdit();assert.equal(a.get('profileLink'),'');
const oldCount=a.get('rooms.length');a.join(-1);assert.equal(a.get('rooms.length'),oldCount);
(async()=>{
 let bitmapClosed=0,canvasReleased=false;
 ctx.createImageBitmap=async()=>({width:1280,height:960,close(){bitmapClosed++}});
 doc.createElement=()=>({width:0,height:0,getContext(){return {drawImage(){}}},toBlob(cb){cb({size:42000,type:'image/jpeg'})}});
 const avatarBlob=await a.prepareAvatarPhoto({type:'image/png',size:500000});assert.equal(avatarBlob.size,42000);bitmapClosed=0;
 const compressed=await a.compressPhoto({type:'image/jpeg',size:500000});assert.equal(compressed.size,42000);assert.equal(bitmapClosed,1);
 await assert.rejects(()=>a.compressPhoto({type:'image/svg+xml',size:100}));
 await assert.rejects(()=>a.compressPhoto({type:'image/jpeg',size:6*1024*1024}));
 a.set("view='chats';chatPerson=3;localMessages={};plus=true");
 await a.choosePhoto({target:{files:[{type:'image/jpeg',size:500000}]}},'sendChat');
 assert.equal(a.get('localMessages[3].at(-1).kind'),'photo');assert.equal(a.get('attachment'),null);
 ctx.MediaRecorder=class {static isTypeSupported(){return true} constructor(){this.state='inactive';this.mimeType='audio/mp4'} start(){this.state='recording'} stop(){this.state='inactive';this.ondataavailable?.({data:new Blob(['voice'],{type:'audio/mp4'})});this.onstop?.()}};
 const originalMic=ctx.navigator.mediaDevices.getUserMedia;ctx.navigator.mediaDevices.getUserMedia=async()=>stream;
 a.set("micHold={id:77,x:0,active:true,handler:'sendChat'}");await a.recordNote('sendChat');
 a.endMicHold({pointerId:77},false);assert.equal(a.get('localMessages[3].at(-1).kind'),'voice');assert.equal(a.get('attachment'),null);
 const sent=a.get('localMessages[3].length');a.set("micHold={id:78,x:0,active:true,handler:'sendChat'}");await a.recordNote('sendChat');a.endMicHold({pointerId:78},true);assert.equal(a.get('localMessages[3].length'),sent);
 a.set("micHold={id:79,x:100,y:200,active:true,handler:'sendChat'}");await a.recordNote('sendChat');a.moveMicHold({pointerId:79,clientX:100,clientY:100});assert.equal(a.get('noteLocked'),true);a.endMicHold({pointerId:79},false);assert.equal(a.get('noteRecording'),true);assert.equal(a.get('localMessages[3].length'),sent);a.finishNote();assert.equal(a.get('localMessages[3].length'),sent+1);assert.equal(a.get('noteLocked'),false);
 a.set("micHold={id:80,x:100,y:200,active:true,handler:'sendChat'}");await a.recordNote('sendChat');a.moveMicHold({pointerId:80,clientX:200,clientY:200});assert.equal(a.get('noteRecording'),true);a.moveMicHold({pointerId:80,clientX:0,clientY:200});assert.equal(a.get('noteRecording'),false);assert.equal(a.get('localMessages[3].length'),sent+1);
 ctx.navigator.mediaDevices.getUserMedia=originalMic;
 a.set("micHold={id:81,x:100,y:200,active:true,handler:'sendChat'}");const pendingNote=a.recordNote('sendChat');a.endMicHold({pointerId:81},false);resolveStream(stream);await pendingNote;assert.equal(a.get('noteRecording'),false);assert.equal(a.get('localMessages[3].length'),sent+1);

 // Regression: permission denial, exhausted device, interrupted track, broken
 // recorder stop, missing stop event, stale permission resolution and retry.
 const normalRecorder=ctx.MediaRecorder;
 ctx.navigator.mediaDevices.getUserMedia=async()=>{throw Object.assign(Error('denied'),{name:'NotAllowedError'})};
 await a.recordNote('sendChat');assert.equal(a.get('noteBusy'),false);assert.equal(a.get('noteRecording'),false);assert(a.get('noteError.length')>0);
 const trackEvents={};let stoppedTracks=0;
 const track={readyState:'live',muted:false,stop(){stoppedTracks++},addEventListener(n,f){trackEvents[n]=f},removeEventListener(n){delete trackEvents[n]}};
 const liveStream={getTracks:()=>[track],getAudioTracks:()=>[track]};
 ctx.navigator.mediaDevices.getUserMedia=async()=>liveStream;
 await a.recordNote('sendChat');assert(a.get('noteRecording'));trackEvents.ended();assert(!a.get('noteRecording'));assert(!a.get('noteBusy'));assert(stoppedTracks>0);assert.equal(a.get('localMessages[3].length'),sent+1);
 await a.recordNote('sendChat');trackEvents.mute();assert(!a.get('noteRecording'));assert.equal(Object.keys(trackEvents).length,0);
 ctx.MediaRecorder=class extends normalRecorder {stop(){throw Error('device lost')}};
 await a.recordNote('sendChat');a.finishNote();assert(!a.get('noteBusy'));assert(!a.get('noteRecording'));assert.equal(a.get('localMessages[3].length'),sent+1);
 ctx.MediaRecorder=normalRecorder;
 await a.recordNote('sendChat');a.get('noteRecorder').stop();assert(!a.get('noteRecording'));assert.equal(a.get('localMessages[3].length'),sent+1,'unexpected stop must not dispatch');
 const oldTimeout=ctx.setTimeout,oldClearTimeout=ctx.clearTimeout;
 const timers=new Map();let timerID=0;
 ctx.setTimeout=(fn,ms)=>{const id=++timerID;timers.set(id,{fn,ms});return id};ctx.clearTimeout=id=>timers.delete(id);
 let resolveLate;ctx.navigator.mediaDevices.getUserMedia=()=>new Promise(r=>resolveLate=r);
 const waiting=a.recordNote('sendChat');[...timers.values()].find(x=>x.ms===30000).fn();assert(!a.get('noteBusy'));
 ctx.navigator.mediaDevices.getUserMedia=async()=>liveStream;
 await a.recordNote('sendChat');const currentRecorder=a.get('noteRecorder');let lateStops=0;
 resolveLate({getTracks:()=>[{stop(){lateStops++}}]});await waiting;assert.equal(lateStops,1);assert.equal(a.get('noteRecorder'),currentRecorder);assert(a.get('noteRecording'));a.stopNote();
 ctx.MediaRecorder=class extends normalRecorder {stop(){this.state='inactive'}};
 await a.recordNote('sendChat');a.finishNote();assert(a.get('noteBusy'));[...timers.values()].find(x=>x.ms===5000).fn();assert(!a.get('noteBusy'));assert(!a.get('noteRecording'));
 ctx.MediaRecorder=normalRecorder;ctx.setTimeout=oldTimeout;ctx.clearTimeout=oldClearTimeout;
 a.set("micHold={id:82,x:200,y:200,active:true,handler:'sendChat'}");await a.recordNote('sendChat');a.moveMicHold({pointerId:82,clientX:100,clientY:50});assert(a.get('noteLocked'),'dominant upward diagonal locks');a.stopNote();
 await a.recordNote('sendChat');a.finishNote();assert.equal(a.get('localMessages[3].length'),sent+2,'retry succeeds after all failures');
 console.log('PASS: voice denial, interruption, stop errors, permission/stop deadlines, stale streams, diagonal gestures and retry.');
 ctx.navigator.mediaDevices.getUserMedia=originalMic;bitmapClosed=1;
 a.go('home');assert(!app.innerHTML.includes('account-hub'));assert(!app.innerHTML.includes('policy-links'));a.go('profile');assert(app.innerHTML.includes('premium-corner'));assert(app.innerHTML.includes('account-hub'));
 ctx.createImageBitmap=async()=>({width:1280,height:960,close(){bitmapClosed++}});
 doc.createElement=()=>({getContext(){return {drawImage(){throw Error('decode failure')}}}});
 await assert.rejects(()=>a.compressPhoto({type:'image/png',size:5000}));assert.equal(bitmapClosed,2);
 a.set('plus=true');a.join(6);
 const pending=a.recordAction();assert(a.get('recordBusy'));
 a.go('home');resolveStream(stream);await pending;
 assert(streamStops>0);assert.equal(a.get('recording'),false);assert.equal(a.get('recordURL'),'');
 a.set("recordURL='blob:old';cinemaURL='blob:movie';localMessages={3:['private']};roomMessages={1:['private']}");
 windowEvents.pagehide();assert(revoked.includes('blob:old'));assert(revoked.includes('blob:movie'));assert.equal(a.get('Object.keys(localMessages).length'),0);assert.equal(app.innerHTML,'');
 windowEvents.pageshow({persisted:true});assert(app.innerHTML.includes('vibe'));
 console.log('PASS: source CSP checks, bilingual views, callback isolation, input escaping/limits, flash cleanup, gameplay, media permission race, blob release, and page lifecycle cleanup.');
 console.log('Not browser, device, transport, penetration, or native iOS validation.');
})().catch(e=>{console.error(e);process.exitCode=1});
