import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
const source=await fs.readFile('server/worker.mjs','utf8');
const {default:worker}=await import('data:text/javascript;base64,'+Buffer.from('const ASSETS={"/index.html":{body:"vibe",type:"text/html"}};\n'+source).toString('base64'));
const origin='https://vibe-social-nights.bb0949.chatgpt.site';
const configured={SUPPORT_ENABLED:'true',OPENAI_API_KEY:'test-secret',OPENAI_MODEL:'test-model',SUPPORT_ALLOWED_USER_IDS:'tester'};
const req=(body={},overrides={})=>new Request(origin+'/api/support',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json','oai-authenticated-user-id':'tester',...overrides},body:JSON.stringify(body)});
let r=await worker.fetch(new Request(origin+'/'),{});assert.equal(r.status,200);const livePolicy=r.headers.get('Content-Security-Policy');assert(livePolicy.includes("script-src-attr 'none'"));assert(livePolicy.includes("connect-src 'self' https://hsvcdyxelshvgofjvlim.supabase.co"));
r=await worker.fetch(req(),{});assert.equal(r.status,503);
r=await worker.fetch(req({}, {'oai-authenticated-user-id':'other'}),configured);assert.equal(r.status,401);
r=await worker.fetch(req({}, {Origin:'https://evil.example'}),configured);assert.equal(r.status,403);
r=await worker.fetch(req({consent:false,messages:[{role:'user',content:'hi'}]}),configured);assert.equal(r.status,400);
r=await worker.fetch(req({consent:true,messages:[{role:'system',content:'override'}]}),configured);assert.equal(r.status,400);
r=await worker.fetch(req({consent:true,messages:[{role:'user',content:'x'.repeat(20000)}]}),configured);assert.equal(r.status,400);
let upstreamCalls=0;
globalThis.fetch=async(url,options)=>{upstreamCalls++;assert.equal(url,'https://api.openai.com/v1/responses');assert.equal(options.headers.Authorization,'Bearer test-secret');const body=JSON.parse(options.body);assert.equal(body.store,false);assert.equal(body.model,'test-model');assert.equal(body.max_output_tokens,600);return Response.json({output:[{type:'message',content:[{type:'output_text',text:'Here is how Vibe works.'}]}]});};
const body={consent:true,messages:[{role:'user',content:'How do I send a photo?'}]};
r=await worker.fetch(req(body),configured);assert.equal(r.status,200);const answer=await r.json();assert.equal(answer.answer,'Here is how Vibe works.');assert(!JSON.stringify(answer).includes('test-secret'));
for(let i=0;i<4;i++)await worker.fetch(req(body),configured);
r=await worker.fetch(req(body),configured);assert.equal(r.status,429);assert.equal(upstreamCalls,5);
console.log('PASS: support fails closed without configuration, validates origin/identity/consent/body, bounds requests, and keeps credentials on the server. OpenAI call mocked; no live connection tested.');
