// Supabase publishable key is public by design. User JWTs stay in HttpOnly cookies.
const SB_URL='https://hsvcdyxelshvgofjvlim.supabase.co';
const SB_KEY='sb_publishable_BCp7IhSHgWkNqXFY0Tk1xA_SE3wIWTg';
const uuidPattern=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const cloudLimits=new Map();
const cloudCookie=(name,value,age)=>`${name}=${encodeURIComponent(value)}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${age}`;
function cloudCookies(req){const out={};for(const c of (req.headers.get('Cookie')||'').split(';')){const i=c.indexOf('=');if(i>0){try{out[c.slice(0,i).trim()]=decodeURIComponent(c.slice(i+1))}catch{}}}return out;}
function cloudResponse(data,status=200,session=null,clear=false){const headers=new Headers({...common,'Content-Type':'application/json; charset=utf-8'});if(session?.access_token){headers.append('Set-Cookie',cloudCookie('__Host-vibe-access',session.access_token,Math.min(session.expires_in||3600,3600)));headers.append('Set-Cookie',cloudCookie('__Host-vibe-refresh',session.refresh_token,604800));}if(clear)for(const k of ['access','refresh'])headers.append('Set-Cookie',cloudCookie('__Host-vibe-'+k,'',0));return new Response(JSON.stringify(data),{status,headers});}
async function sbFetch(path,token,method='GET',data,extra={}){const headers={apikey:SB_KEY,...(token?{Authorization:'Bearer '+token}:{}),...extra};if(data!==undefined&&!(data instanceof Uint8Array)){headers['Content-Type']='application/json';data=JSON.stringify(data);}return fetch(SB_URL+path,{method,headers,body:data,signal:AbortSignal.timeout(15000),redirect:'error'});}
async function sbData(path,token,method='GET',body,extra={}){const r=await sbFetch(path,token,method,body,extra);const data=r.status===204?null:await r.json().catch(()=>null);if(!r.ok){const e=Error('upstream');e.status=r.status;e.code=data?.error_code||data?.code||'request_failed';throw e;}return data;}
async function cloudIdentity(req){const c=cloudCookies(req);let token=c['__Host-vibe-access'],session=null,user=null;if(token){const r=await sbFetch('/auth/v1/user',token);if(r.ok)user=await r.json();}
 if(!user&&c['__Host-vibe-refresh']){const r=await sbFetch('/auth/v1/token?grant_type=refresh_token',null,'POST',{refresh_token:c['__Host-vibe-refresh']});if(r.ok){session=await r.json();token=session.access_token;user=session.user;}}
 return user?.id?{user,token,session}:null;
}
function cloudRate(req,action,max=60){const key=(req.headers.get('CF-Connecting-IP')||'unknown')+':'+action,now=Date.now();for(const [k,v]of cloudLimits)if(v.until<now)cloudLimits.delete(k);const x=cloudLimits.get(key)||{n:0,until:now+60000};if(x.n>=max||cloudLimits.size>5000)return false;x.n++;cloudLimits.set(key,x);return true;}
async function cloudRoute(req,env,url){const action=url.pathname.slice('/api/cloud/'.length),method=req.method;
 if(!['GET','POST','DELETE','PATCH'].includes(method))return cloudResponse({error:'method_not_allowed'},405);
 if(method!=='GET'&&req.headers.get('Origin')!==url.origin)return cloudResponse({error:'forbidden_origin'},403);
 if(method!=='GET'&&!cloudRate(req,action,action.startsWith('auth')?8:60))return cloudResponse({error:'rate_limited'},429);
 try{
  if(['auth/login','auth/signup','auth/recover','auth/verify','auth/otp','auth/resend'].includes(action)&&method==='POST'){
   const b=await readBody(req);if(typeof b.email!=='string'||b.email.length>254||!/^\S+@\S+\.\S+$/.test(b.email))return cloudResponse({error:'invalid_email'},400);
   let path,payload;
   if(action==='auth/verify'){if(typeof b.token!=='string'||!/^\d{6,10}$/.test(b.token))return cloudResponse({error:'invalid_code'},400);path='/auth/v1/verify';payload={email:b.email,token:b.token,type:'email'};}
   else if(action==='auth/otp'){path='/auth/v1/otp';payload={email:b.email,create_user:false};}
   else if(action==='auth/resend'){path='/auth/v1/resend';payload={email:b.email,type:'signup'};}
   else if(action==='auth/recover'){path='/auth/v1/recover?redirect_to='+encodeURIComponent(url.origin+'/?recovery=1');payload={email:b.email};}
   else{if(typeof b.password!=='string'||b.password.length<8||b.password.length>128)return cloudResponse({error:'invalid_password'},400);if(action==='auth/signup'&&(b.accepted!==true||typeof b.name!=='string'||!b.name.trim()||b.name.trim().length>24))return cloudResponse({error:'consent_required'},400);path=action==='auth/signup'?'/auth/v1/signup?redirect_to='+encodeURIComponent(url.origin):'/auth/v1/token?grant_type=password';payload={email:b.email,password:b.password,...(action==='auth/signup'?{data:{display_name:b.name.trim(),community_accepted_at:new Date().toISOString(),policies_accepted_at:new Date().toISOString(),terms_version:'2026.09',privacy_version:'2026.09',community_guidelines_version:'2026.09'}}:{})};}
   const result=await sbData(path,null,'POST',payload);const session=result?.access_token?result:null;return cloudResponse({ok:true,confirmation_required:action==='auth/signup'&&!result?.access_token},200,session);
  }
  // Supabase confirmation/recovery redirect gives tokens in the fragment; exchange
  // them for same-origin HttpOnly cookies only after /user verifies the token.
  if(action==='auth/callback'&&method==='POST'){const b=await readBody(req);if(typeof b.access_token!=='string'||typeof b.refresh_token!=='string')return cloudResponse({error:'invalid_session'},400);let session;try{session=await sbData('/auth/v1/token?grant_type=refresh_token',null,'POST',{refresh_token:b.refresh_token});}catch{session=null;}const user=session?.user;if(!user?.id)return cloudResponse({error:'invalid_session'},401);return cloudResponse({ok:true},200,session);}
  const identity=await cloudIdentity(req);
  if(action==='auth/session'&&method==='GET')return cloudResponse({user:identity?{id:identity.user.id,email:identity.user.email,display_name:identity.user.user_metadata?.display_name||''}:null},200,identity?.session);
  if(!identity)return cloudResponse({error:'sign_in_required'},401,null,true);
  const {user,token,session}=identity;const uid=user.id;
  const done=(value,status=200)=>cloudResponse(value,status,session);
  const rest=(table,query='',method='GET',body)=>sbData('/rest/v1/'+table+query,token,method,body,{'Prefer':method==='POST'&&['vibe_settings','vibe_profile_details','vibe_profile_photos'].includes(table)?'return=representation,resolution=merge-duplicates':method==='POST'&&['vibe_members','vibe_blocks','vibe_likes'].includes(table)?'return=representation,resolution=ignore-duplicates':'return=representation'});
  if(action==='auth/logout'&&method==='POST'){await sbData('/auth/v1/logout?scope=global',token,'POST');return cloudResponse({ok:true},200,null,true);}
  if(action==='auth/password'&&method==='POST'){const b=await readBody(req);if(typeof b.password!=='string'||b.password.length<8||b.password.length>128)return done({error:'invalid_password'},400);await sbData('/auth/v1/user',token,'PUT',{password:b.password});await sbData('/auth/v1/logout?scope=others',token,'POST');return done({ok:true});}
  if(action==='profile'){
   if(method==='GET'){let rows=await rest('vibe_profiles','?id=eq.'+uid);if(!rows.length)rows=await rest('vibe_profiles','','POST',{id:uid,display_name:String(user.user_metadata?.display_name||'Vibe member').slice(0,24)});const [details,photos,prompts,completion]=await Promise.all([rest('vibe_profile_details','?user_id=eq.'+uid),rest('vibe_profile_photos','?user_id=eq.'+uid+'&order=slot.asc'),rest('vibe_profile_prompts','?user_id=eq.'+uid+'&order=slot.asc'),sbData('/rest/v1/rpc/vibe_profile_completion',token,'POST',{})]);return done({profile:rows[0],details:details[0]||null,photos,prompts,completion});}
   if(method==='PATCH'){const b=await readBody(req);if(typeof b.display_name!=='string'||!b.display_name.trim()||b.display_name.trim().length>24||typeof b.bio!=='string'||b.bio.length>160||!b.data||typeof b.data!=='object'||Array.isArray(b.data))return done({error:'invalid_profile'},400);return done({profile:(await rest('vibe_profiles','?id=eq.'+uid,'PATCH',{display_name:b.display_name.trim(),bio:b.bio,data:b.data}))[0]});}
  }
  if(action==='people'&&method==='GET'){const search=(url.searchParams.get('q')||'').trim().slice(0,40).replace(/[%_*(),.]/g,'');return done({people:await rest('vibe_profiles','?select=id,display_name,bio,data&id=neq.'+uid+'&limit=50'+(search?'&display_name=ilike.'+encodeURIComponent('*'+search+'*'):''))});}
  if(action==='settings'){if(method==='GET'){const s=(await rest('vibe_settings','?user_id=eq.'+uid))[0]||{};return done({settings:{...(s.data||{}),appearance:s.theme||'dark',smartPhotos:!!s.smart_photos_enabled,hideAge:!!s.hide_age,hideDistance:!!s.hide_distance}});}if(method==='POST'){const b=await readBody(req),theme=['dark','light'].includes(b.appearance)?b.appearance:'dark';await rest('vibe_settings','','POST',{user_id:uid,data:b,theme,smart_photos_enabled:!!b.smartPhotos,hide_age:!!b.hideAge,hide_distance:!!b.hideDistance});return done({ok:true});}}
  if(action==='onboarding'&&method==='GET')return done({status:await sbData('/rest/v1/rpc/vibe_onboarding_status',token,'POST',{})});
  if(action==='onboarding'&&method==='POST'){const b=await readBody(req),step=Number(b.step);if(!Number.isInteger(step)||step<1||step>3)return done({error:'invalid_step'},400);const status=await sbData('/rest/v1/rpc/vibe_onboarding_step',token,'POST',{p_step:step,p_values:Array.isArray(b.values)?b.values:[],p_types:Array.isArray(b.types)?b.types:[]});return done({status});}
  if(action==='profile-details'&&method==='POST'){const b=await readBody(req);await rest('vibe_profile_details','','POST',{user_id:uid,living_in:String(b.living_in||'').slice(0,120),height_cm:b.height_cm||null,job:String(b.job||'').slice(0,120),education:String(b.education||'').slice(0,160),basics:b.basics||{},lifestyle:b.lifestyle||{}});return done({ok:true});}
  if(action==='profile-prompts'&&method==='POST'){const b=await readBody(req);await rest('vibe_profile_prompts','?user_id=eq.'+uid,'DELETE');for(const [slot,x] of (Array.isArray(b.prompts)?b.prompts:[]).slice(0,3).entries())if(x?.question&&x?.answer)await rest('vibe_profile_prompts','','POST',{user_id:uid,slot,question:String(x.question).slice(0,160),answer:String(x.answer).slice(0,600)});return done({ok:true});}
  if(action==='profile-photo'&&method==='POST'){let b;try{b=await readBody(req);}catch{return done({error:'invalid_request'},400);}if(!b||typeof b!=='object'||Array.isArray(b))return done({error:'invalid_request'},400);if(!Number.isInteger(b.slot)||b.slot<0||b.slot>5||typeof b.object_path!=='string'||b.object_path.length>250||b.object_path.includes('..')||!b.object_path.startsWith(uid+'/'))return done({error:'invalid_photo'},400);await rest('vibe_profile_photos','','POST',{user_id:uid,slot:b.slot,object_path:b.object_path});return done({ok:true});}
  if(action==='rooms'){if(method==='GET')return done({rooms:await rest('vibe_rooms','?order=created_at.desc&limit=100')});if(method==='POST'){let b;try{b=await readBody(req);}catch{return done({error:'invalid_request'},400);}if(!b||typeof b!=='object'||Array.isArray(b))return done({error:'invalid_request'},400);const title=typeof b.title==='string'?b.title.trim():'';const category=Number(b.category);const kind=String(b.kind||'voice');if(title.length<1||title.length>60||!Number.isInteger(category)||category<1||category>5||!['voice','flash','cinema','game','echo'].includes(kind))return done({error:'invalid_room'},400);const rows=await rest('vibe_rooms','','POST',{owner_id:uid,title,category,kind});await rest('vibe_members','','POST',{room_id:rows[0].id,user_id:uid});return done({room:rows[0]},201);}if(method==='DELETE'){const id=url.searchParams.get('id');if(!uuidPattern.test(id||''))return done({error:'invalid_id'},400);await rest('vibe_rooms','?id=eq.'+id,'DELETE');return done({ok:true});}}
  if(action==='membership'){const id=url.searchParams.get('room');if(!uuidPattern.test(id||''))return done({error:'invalid_id'},400);if(method==='POST'){await rest('vibe_members','','POST',{room_id:id,user_id:uid});return done({ok:true});}if(method==='DELETE'){await rest('vibe_members','?room_id=eq.'+id+'&user_id=eq.'+uid,'DELETE');return done({ok:true});}if(method==='GET')return done({members:await rest('vibe_members','?room_id=eq.'+id+'&select=user_id,vibe_profiles(id,display_name,data)&limit=100')});}
  if(action==='messages'){
   if(method==='GET'){const room=url.searchParams.get('room'),peer=url.searchParams.get('peer');if(!uuidPattern.test(room||peer||''))return done({error:'invalid_id'},400);const older=url.searchParams.get('before');if(older&&!Number.isFinite(Date.parse(older)))return done({error:'invalid_time'},400);const query=room?'room_id=eq.'+room:'room_id=is.null&or=(and(sender_id.eq.'+uid+',receiver_id.eq.'+peer+'),and(sender_id.eq.'+peer+',receiver_id.eq.'+uid+'))';const rows=await rest('messages','?select=*,message_reactions(user_id,emoji)&'+query+'&order=created_at.desc&limit=60'+(older?'&created_at=lt.'+encodeURIComponent(older):''));return done({messages:rows.map(x=>({...x,author_id:x.sender_id,recipient_id:x.receiver_id,body:x.content}))});}
   if(method==='POST'){let b;try{b=await readBody(req);}catch{return done({error:'invalid_request'},400);}if(!b||typeof b!=='object'||Array.isArray(b))return done({error:'invalid_request'},400);const kind=b.kind||'text',body=typeof b.body==='string'?b.body:'',object_path=typeof b.object_path==='string'&&b.object_path?b.object_path:null,room_id=b.room_id||null,recipient_id=b.recipient_id||null,client_message_id=typeof b.client_message_id==='string'&&b.client_message_id&&b.client_message_id.length<=64?b.client_message_id:null;if(body.length>2000||(kind==='text'&&!body.trim())||!['text','photo','voice'].includes(kind)||(kind!=='text'&&!object_path)||(room_id&&recipient_id)||(!room_id&&!recipient_id)||(recipient_id&&!uuidPattern.test(recipient_id))||(room_id&&!uuidPattern.test(room_id)))return done({error:'invalid_message'},400);const row={id:uuidPattern.test(b.id||'')?b.id:crypto.randomUUID(),sender_id:uid,room_id,receiver_id:recipient_id,kind,content:body,object_path,client_message_id};let data;try{data=await sbData('/rest/v1/messages',token,'POST',row,{'Prefer':'return=representation'});}catch(e){if(client_message_id&&e.code==='23505'){const existing=await rest('messages','?client_message_id=eq.'+encodeURIComponent(client_message_id));if(existing[0])return done({message:{...existing[0],author_id:existing[0].sender_id,recipient_id:existing[0].receiver_id,body:existing[0].content}},200);}throw e;}return done({message:{...data[0],author_id:data[0].sender_id,recipient_id:data[0].receiver_id,body:data[0].content}},201);}
   if(method==='DELETE'){const id=url.searchParams.get('id');if(!uuidPattern.test(id||''))return done({error:'invalid_id'},400);await rest('messages','?id=eq.'+id,'DELETE');return done({ok:true});}
  }
  if(action==='inbox'&&method==='GET'){const rows=await rest('messages','?room_id=is.null&or=(sender_id.eq.'+uid+',receiver_id.eq.'+uid+')&order=created_at.desc&limit=200');return done({messages:rows.map(x=>({...x,author_id:x.sender_id,recipient_id:x.receiver_id,body:x.content}))});}
  if(action==='notifications'){if(method==='GET')return done({items:await rest('notifications','?user_id=eq.'+uid+'&order=created_at.desc&limit=200')});if(method==='PATCH'){const b=await readBody(req),actor=String(b.actor_id||'');if(!uuidPattern.test(actor))return done({error:'invalid_id'},400);await rest('notifications','?user_id=eq.'+uid+'&actor_id=eq.'+actor+'&read_at=is.null','PATCH',{read_at:new Date().toISOString()});return done({ok:true});}}
  if(action==='reaction'){const id=url.searchParams.get('message');if(!uuidPattern.test(id||''))return done({error:'invalid_id'},400);if(method==='POST'){await sbData('/rest/v1/message_reactions',token,'POST',{message_id:id,user_id:uid,emoji:'❤️'},{'Prefer':'return=minimal,resolution=merge-duplicates'});return done({ok:true});}if(method==='DELETE'){await rest('message_reactions','?message_id=eq.'+id+'&user_id=eq.'+uid,'DELETE');return done({ok:true});}}
  if(action==='likes'||action==='blocks'){const table=action==='likes'?'vibe_likes':'vibe_blocks',field=action==='likes'?'room_id':'blocked_id';if(method==='GET')return done({items:await rest(table,'?user_id=eq.'+uid)});const id=url.searchParams.get('id');if(!uuidPattern.test(id||''))return done({error:'invalid_id'},400);if(method==='POST'){await rest(table,'','POST',{user_id:uid,[field]:id});return done({ok:true});}if(method==='DELETE'){await rest(table,'?user_id=eq.'+uid+'&'+field+'=eq.'+id,'DELETE');return done({ok:true});}}
  if(action==='reports'){if(method==='GET')return done({reports:await rest('vibe_reports','?order=created_at.desc&limit=100')});if(method==='POST'){let b;try{b=await readBody(req);}catch{return done({error:'invalid_request'},400);}if(!b||typeof b!=='object'||Array.isArray(b))return done({error:'invalid_request'},400);const target_kind=typeof b.target_kind==='string'?b.target_kind:'';const target_id=typeof b.target_id==='string'?b.target_id:'';const reason=typeof b.reason==='string'?b.reason:'';const details=typeof b.details==='string'?b.details:'';if(!['user','room','message','support'].includes(target_kind)||!target_id||target_id.length>100||!reason.trim()||reason.length>100||details.length>2000)return done({error:'invalid_report'},400);const rows=await rest('vibe_reports','','POST',{reporter_id:uid,target_kind,target_id,reason,details});return done({report:rows[0]},201);}}
  if(action==='upload'&&method==='POST'){const scope=url.searchParams.get('scope'),target=url.searchParams.get('target');if(!['profile','room','dm'].includes(scope)||!uuidPattern.test(target||''))return done({error:'invalid_target'},400);const mime=(req.headers.get('Content-Type')||'').split(';')[0],ext={'image/jpeg':'jpg','image/png':'png','image/webp':'webp','audio/webm':'webm','audio/mp4':'m4a','audio/ogg':'ogg','audio/mpeg':'mp3','video/mp4':'mp4'}[mime];if(!ext||scope==='profile'&&!mime.startsWith('image/'))return done({error:'invalid_media'},415);const reader=req.body?.getReader();if(!reader)return done({error:'empty_media'},400);let size=0,parts=[];while(true){const x=await reader.read();if(x.done)break;size+=x.value.length;if(size>8*1024*1024){await reader.cancel();return done({error:'file_too_large'},413);}parts.push(x.value);}if(!size)return done({error:'empty_media'},400);const bytes=new Uint8Array(size);let offset=0;for(const x of parts){bytes.set(x,offset);offset+=x.length;}const path=uid+'/'+scope+'/'+target+'/'+crypto.randomUUID()+'.'+ext;await sbData('/storage/v1/object/vibe-media/'+path,token,'POST',bytes,{'Content-Type':mime});return done({path,url:'/api/cloud/file?path='+encodeURIComponent(path)},201);}
  if(action==='file'&&method==='GET'){const path=url.searchParams.get('path')||'';if(!/^[a-zA-Z0-9/._-]{1,250}$/.test(path)||path.includes('..'))return done({error:'invalid_path'},400);const r=await sbFetch('/storage/v1/object/authenticated/vibe-media/'+path,token);if(!r.ok)return done({error:'media_unavailable'},r.status===404?404:403);return new Response(r.body,{headers:{...common,'Content-Type':r.headers.get('Content-Type')||'application/octet-stream','Content-Disposition':'inline','Cache-Control':'private, no-store'}});}
  return done({error:'not_found'},404);
 }catch(e){console.error('cloudRoute failed',e?.code||e?.message||e);const status=e.status===400||e.status===422?400:e.status===401?401:e.status===403?403:e.status===429?429:503;return cloudResponse({error:e.code||'temporarily_unavailable'},status);}
}
