-- DEPRECATED: this legacy schema file must NOT be reapplied to production.
--
-- The authoritative live schema is documented in:
--   docs/SUPABASE-SCHEMA-INVENTORY.md
--
-- Versioned Supabase migrations live in:
--   supabase/migrations/
--
-- Apply production changes only through reviewed migration files and the
-- gated Supabase Migrate workflow.
