#!/usr/bin/env node
/**
 * scripts/build.mjs
 * ---------------------------------------------------------------------------
 * Bundles the Vibe client sources into ONE deferred script and renders the
 * entry page that loads it.
 *
 * Concatenation order (everything shares a single closure / scope):
 *
 *   1. public/app.js            framework helpers: on(), render(), t(), esc(),
 *                               authScreen(), …
 *   2. public/cloud-ui.js       cloud UI pieces
 *   3. public/master-spec.js    base views (incl. the original cloudRecoveryView)
 *   4. public/auth-spec.js      auth spec / OTP recovery flow (overrides recovery)
 *   5. public/auth-ui-secure.js CSP-safe override of cloudRecoveryView()
 *
 * auth-ui-secure.js MUST stay concatenated after auth-spec.js and before the
 * render bootstrap: it only replaces the recovery view and binds its handlers
 * through on(), because the page policy is script-src-attr 'none' (no textual
 * inline event attributes anywhere).
 *
 * The bundle is loaded with an external <script src> tag on purpose — inlining
 * the script would require 'unsafe-inline' in the CSP.
 *
 * Outputs (adjust the constants below if the deployed paths differ):
 *   dist/app.bundle.js   concatenated sources
 *   dist/index.html      rendered page (from public/index.html when present)
 * ---------------------------------------------------------------------------
 */

import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const PUBLIC_DIR = join(ROOT, 'public');
const OUT_DIR = join(ROOT, 'dist');

/** Sources in concatenation order — order matters, see the header comment. */
const SOURCES = [
  { file: 'app.js', label: 'app (helpers: on, render, t, esc, authScreen)' },
  { file: 'cloud-ui.js', label: 'cloud-ui' },
  { file: 'master-spec.js', label: 'master-spec (base views)' },
  { file: 'auth-spec.js', label: 'auth-spec (OTP recovery flow)' },
  { file: 'auth-ui-secure.js', label: 'auth-ui-secure (CSP-safe cloudRecoveryView override)' },
];

const BUNDLE_FILE = 'app.bundle.js';
const PAGE_FILE = 'index.html';
const PLACEHOLDER = /<!--\s*vibe:bundle\s*-->/;

function banner() {
  return '/* Vibe bundle — generated by scripts/build.mjs. Do not edit by hand. */\n';
}

async function readSource(source) {
  const path = join(PUBLIC_DIR, source.file);
  if (!existsSync(path)) {
    throw new Error(`Missing required source file: public/${source.file}`);
  }
  const code = await readFile(path, 'utf8');
  const header = `/* ---- public/${source.file} — ${source.label} ---- */`;
  return `${header}\n${code.replace(/\s+$/, '')}\n`;
}

async function buildBundle() {
  const parts = [];
  for (const source of SOURCES) {
    parts.push(await readSource(source));
  }
  return banner() + '\n' + parts.join('\n');
}

function scriptTag(bundleName) {
  return `<script src="./${bundleName}" defer></script>`;
}

async function renderPage(bundleName) {
  const tag = scriptTag(bundleName);
  const templatePath = join(PUBLIC_DIR, 'index.html');

  if (existsSync(templatePath)) {
    let html = await readFile(templatePath, 'utf8');
    if (PLACEHOLDER.test(html)) {
      return html.replace(PLACEHOLDER, tag);
    }
    if (html.includes('</body>')) {
      return html.replace('</body>', `  ${tag}\n</body>`);
    }
    return `${html}\n${tag}\n`;
  }

  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Vibe</title>
</head>
<body>
  <div id="app"></div>
  ${tag}
</body>
</html>
`;
}

async function main() {
  const bundle = await buildBundle();
  const page = await renderPage(BUNDLE_FILE);

  await mkdir(OUT_DIR, { recursive: true });
  await writeFile(join(OUT_DIR, BUNDLE_FILE), bundle, 'utf8');
  await writeFile(join(OUT_DIR, PAGE_FILE), page, 'utf8');

  console.log(
    `vibe build: ${SOURCES.map((s) => s.file).join(' + ')} -> dist/${BUNDLE_FILE} ` +
      `(${bundle.length} bytes) + dist/${PAGE_FILE}`
  );
}

main().catch((err) => {
  console.error('vibe build failed:', err && err.message ? err.message : err);
  process.exitCode = 1;
});
